# stage 1 : build
FROM node:24 as builder

WORKDIR /client

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

#stage 2: production 
FROM nginx:alpine

COPY --from=builder /client/dist /usr/share/nginx/html

CMD [ "nginx", "-g", "daemon off;" ]